name: 'ğŸ¢ Next.js'

on:
  push:

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›¬
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Cache node_modules ğŸ§ 
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Setup Node âš™ï¸
        uses: actions/setup-node@v6
        with:
          node-version: 22.5

      - name: Configure NPM for GitHub Packages ğŸ”‘
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          echo "@skrteeeeee:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Install dependencies ğŸ“©
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Next.js ğŸ“¦
        run: npm run build

      - name: Lint code ğŸ’…
        run: npm run lint

      - name: Cache Next.js build âš¡
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('package-lock.json') }}
